project:
  type: website
mainfont: "Atkinson Hyperlegible"
  
logo: LMLLOGO.png



website:
  title: "LittleMonkeyBlog"
  favicon: images/LMLLOGO.png
  site-url: https://littlemonkeylab.github.io/LittleMonkeyBlog/
  description: "Monkeying about"
  repo-url: https://github.com/LittleMonkeyLab/LittleMonkeyBlog/
  twitter-card: true
  margin-header: subscribe.html
  navbar:
    background: "#eeeeee"
    logo: images/LMLLOGO.png
    right:
      - about.qmd
      - icon: rss
        href: index.xml
      - icon: github
        aria-label: github
        href: https://github.com/LittleMonkeyLab/LittleMonkeyBlog/
      - icon: twitter
        aria-label: twitter
        href: https://twitter.com/littlemonkeylab/
  page-footer:
    left: "Blog made with ðŸ’œ and [Quarto](https://quarto.org/), by Gordon Wright License: [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)."
    right: "Study hard what interests you the most in the most undisciplined, irreverent and original manner possible - Richard Feynman"
  google-analytics: "G-JCNXQM9CGQ"
format:
  html:
    theme: 
      - simplex
      - custom.scss
    css: styles.css

comments: 
  hypothesis: true
  utterances: 
    repo: Littlemonkeylab/blogcomments



editor: visual

